name: Python Lambda Template CI/CD

on:
    repository_dispatch:
        types: [create-backstage-component]
    workflow_dispatch:
        inputs:
            function_name:
                description: 'Lambda Function Name'
                required: true
                default: 'myLambdaFunction'
            aws_region:
                description: 'AWS Region'
                required: true
                default: 'us-east-1'
            memory_size:
                description: 'Memory Size (MB)'
                required: true
                default: '512'
            timeout:
                description: 'Timeout (Seconds)'
                required: true
                default: '300'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: .
        env:
            AWS_REGION: "{{ cookiecutter.aws_region }}"
            FUNCTION_NAME: "{{ cookiecutter.function_name }}"
            MEMORY_SIZE: "{{ cookiecutter.memory_size }}"
            TIMEOUT: "{{ cookiecutter.timeout }}"
            ECR_REPOSITORY: "{{ cookiecutter.ecr_repository_name }}"
            IMAGE_NAME: "{{ cookiecutter.project_name }}"

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              run: |
                echo "Setting up Python environment"
                # Try to use the latest Python version
                if command -v python3 >/dev/null 2>&1; then
                  echo "Using Python 3"
                  if ! python3 -m pip --version >/dev/null 2>&1; then
                    echo "Python 3 is installed but pip is not"
                    sudo apt-get update
                    sudo apt-get install python3-pip
                  fi
                else
                  echo "Python 3 is not installed, installing Python 3"
                  sudo apt-get update
                  sudo apt-get install -y python3 python3-pip
                fi
                echo "Python and pip are set up"

            - name: Show Configuration
              run: |
                echo "Python Hello World Lambda Deployment"
                echo "Function Name: $FUNCTION_NAME"
                echo "AWS Region: $AWS_REGION"
                echo "Memory Size: $MEMORY_SIZE MB"
                echo "Timeout: $TIMEOUT seconds"
                echo "ECR Repository: $ECR_REPOSITORY"
                echo "Working Directory: $(pwd)
                echo "Image Name: $IMAGE_NAME"

            - name: Install Dependencies
              run: |
                echo "Installing dependencies"
                # Use --break-system-packages for CI environment
                python3 -m pip install --upgrade pip --break-system-packages
                python3 -m pip install boto3>=1.34.0 --break-system-packages
                echo "Dependencies installed successfully"





            - name: Build and Deploy
              run: |
                echo "Building and deploying the function"
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                python -m pip install awscli --upgrade
                aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_REGION.dkr.ecr.$AWS_REGION.amazonaws.com
                docker build -t $ECR_REPOSITORY/$IMAGE_NAME .
                docker tag $ECR_RE

    