apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "{{ cookiecutter.instanceName }}"
  description: EC2 instance provisioned using Backstage scaffolder
  annotations:
    github.com/project-slug: "{{ cookiecutter.destination.owner + '/' + cookiecutter.destination.repo }}"
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: "{{ cookiecutter.instanceName }}"
    github.com/workflows: 'EC2_Instance.yml'
    # sonarqube.org/project-key: {{ cookiecutter.instance_name }}
  tags:
    - aws
    - ec2
    - "{{ cookiecutter.region }}"
    - "{{ cookiecutter.instanceType }}"
    - infrastructure
  links:
    - url: https://github.com/{{ cookiecutter.destination.owner }}/{{ cookiecutter.destination.repo }}
      title: GitHub Repo
      icon: github
    - url: https://console.aws.amazon.com/ec2/v2/home?region={{ cookiecutter.region }}
      title: AWS Console
      icon: web

spec:
  type: resource
  owner: platform
  lifecycle: experimental
  system: cloud-infra
  dependsOn: []
  providesApis: []
  consumesApis: []

